apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: ProxmoxCluster
metadata:
  name: mycluster
  namespace: default
spec:
  controlPlaneEndpoint:
    host: 192.168.1.30
  ipv4Config:
    addresses:
    - 192.168.1.31-192.168.1.35
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: mycluster
  namespace: default
  labels:
    cni: calico  
spec: {}