apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlane
metadata:
  name: mycluster-control-plane
  namespace: default
spec:
  replicas: 1
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: ProxmoxMachineTemplate
metadata:
  name: mycluster-control-plane
  namespace: default
spec:
  template:
    spec:
      memoryMiB: 2048
      numCores: 2
      disks:
        bootVolume:
          sizeGb: 20