apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cluster-api-dev

resources:
- ../../base

namePrefix: dev-

patchesStrategicMerge:
- cluster-patch.yaml
- control-plane-patch.yaml
- workers-patch.yaml

commonLabels:
  environment: dev