apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

# Убираем namePrefix - будем использовать явные имена в патчах
# namePrefix: dev-

# Исправляем labels (вместо commonLabels)
labels:
- pairs:
    environment: dev
    cluster.x-k8s.io/cluster-name: dev-mycluster

resources:
- ../../base

# Исправляем patches (вместо patchesStrategicMerge)
patches:
- path: cluster-patch.yaml
- path: cluster-name-patch.yaml
- path: controlplane-name-patch.yaml
- path: machinetemplate-cp-name-patch.yaml
- path: machinetemplate-worker-name-patch.yaml
- path: machinedeployment-name-patch.yaml
- path: kubeadmconfigtemplate-name-patch.yaml