apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: mycluster-workers
  namespace: default
spec:
  replicas: 1
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: ProxmoxMachineTemplate
metadata:
  name: mycluster-worker
  namespace: default
spec:
  template:
    spec:
      memoryMiB: 2048
      numCores: 1
      disks:
        bootVolume:
          sizeGb: 20