apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: myproxmoxcluster-workers
spec:
  replicas: 4
  clusterName: dev-myproxmoxcluster
  template:
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
          name: dev-myproxmoxcluster-worker
      clusterName: dev-myproxmoxcluster
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
        kind: ProxmoxMachineTemplate
        name: dev-myproxmoxcluster-worker
      
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: ProxmoxMachineTemplate
metadata:
  name: myproxmoxcluster-worker
spec:
  template:
    spec:
      memoryMiB: 2048
      numCores: 1
      disks:
        bootVolume:
          sizeGb: 20