apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: myproxmoxcluster-workers
spec:
  replicas: 1
  template:
    spec:
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
        kind: ProxmoxMachineTemplate
        name: dev-myproxmoxcluster-worker
      version: v1.32.0
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: ProxmoxMachineTemplate
metadata:
  name: myproxmoxcluster-worker
spec:
  template:
    spec:
      memoryMiB: 2048
      numCores: 1
      disks:
        bootVolume:
          sizeGb: 20