apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: myproxmoxcluster
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 10.244.0.0/16
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: ProxmoxCluster
metadata:
  name: myproxmoxcluster
spec:
  controlPlaneEndpoint:
    host: 192.168.1.40
    port: 6443
  ipv4Config:
    addresses:
    - 192.168.1.41-192.168.1.50
    gateway: 192.168.1.1
    prefix: 24
  allowedNodes:
  - pimox1
  - pimox2