apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: myproxmoxcluster-workers
spec:
  replicas: 3
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: ProxmoxMachineTemplate
metadata:
  name: myproxmoxcluster-worker
spec:
  template:
    spec:
      memoryMiB: 8192
      numCores: 4
      disks:
        bootVolume:
          sizeGb: 60