apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: mycluster-workers
  namespace: default
spec:
  replicas: 3
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
kind: ProxmoxMachineTemplate
metadata:
  name: mycluster-worker
  namespace: default
spec:
  template:
    spec:
      memoryMiB: 8192
      numCores: 4
      disks:
        bootVolume:
          sizeGb: 100