apiVersion: addons.cluster.x-k8s.io/v1beta1
kind: ClusterResourceSet
metadata:
  name: cilium-crs
  namespace: default
spec:
  strategy: ApplyOnce
  clusterSelector:
    matchLabels:
      cni: cilium
  resources:
  - name: cilium-addon
    kind: ConfigMap