apiVersion: v1
kind: ConfigMap
metadata:
  name: cilium-addon
  namespace: default
data:
  cilium.yaml: |
    ---
    # Source: cilium/templates/cilium-agent/serviceaccount.yaml
    apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: "cilium"
      namespace: kube-system
    ---
    # Source: cilium/templates/cilium-operator/serviceaccount.yaml
    apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: "cilium-operator"
      namespace: kube-system
    ---
    apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    metadata:
      name: cilium
    rules:
    - apiGroups:
      - networking.k8s.io
      resources:
      - networkpolicies
      verbs:
      - get
      - list
      - watch
    - apiGroups:
      - discovery.k8s.io
      resources:
      - endpointslices
      verbs:
      - get
      - list
      - watch
    - apiGroups:
      - ""
      resources:
      - namespaces
      - services
      - pods
      - endpoints
      - nodes
      verbs:
      - get
      - list
      - watch
    - apiGroups:
      - ""
      resources:
      - pods
      - nodes
      verbs:
      - update
    - apiGroups:
      - ""
      resources:
      - pods/status
      verbs:
      - patch
    ---
    apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    metadata:
      name: cilium-operator
    rules:
    - apiGroups:
      - ""
      resources:
      - pods
      verbs:
      - get
      - list
      - watch
      - delete
    - apiGroups:
      - ""
      resources:
      - nodes
      verbs:
      - list
      - watch
    - apiGroups:
      - ""
      resources:
      - services
      - endpoints
      verbs:
      - get
      - list
      - watch
    - apiGroups:
      - networking.k8s.io
      resources:
      - networkpolicies
      verbs:
      - get
      - list
      - watch
    ---
    apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    metadata:
      name: cilium
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: cilium
    subjects:
    - kind: ServiceAccount
      name: cilium
      namespace: kube-system
    ---
    apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    metadata:
      name: cilium-operator
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: cilium-operator
    subjects:
    - kind: ServiceAccount
      name: cilium-operator
      namespace: kube-system
    ---
    apiVersion: apps/v1
    kind: DaemonSet
    metadata:
      name: cilium
      namespace: kube-system
      labels:
        k8s-app: cilium
    spec:
      selector:
        matchLabels:
          k8s-app: cilium
      updateStrategy:
        rollingUpdate:
          maxUnavailable: 2
        type: RollingUpdate
      template:
        metadata:
          labels:
            k8s-app: cilium
        spec:
          containers:
          - name: cilium-agent
            image: quay.io/cilium/cilium:v1.16.1
            imagePullPolicy: IfNotPresent
            command:
            - cilium-agent
            args:
            - --config-dir=/tmp/cilium/config-map
            startupProbe:
              httpGet:
                host: "127.0.0.1"
                path: /healthz
                port: 9879
                scheme: HTTP
                httpHeaders:
                - name: "brief"
                  value: "true"
              failureThreshold: 105
              periodSeconds: 2
              successThreshold: 1
              timeoutSeconds: 5
            livenessProbe:
              httpGet:
                host: "127.0.0.1"
                path: /healthz
                port: 9879
                scheme: HTTP
                httpHeaders:
                - name: "brief"
                  value: "true"
              periodSeconds: 30
              successThreshold: 1
              failureThreshold: 10
              timeoutSeconds: 5
            readinessProbe:
              httpGet:
                host: "127.0.0.1"
                path: /healthz
                port: 9879
                scheme: HTTP
                httpHeaders:
                - name: "brief"
                  value: "true"
              periodSeconds: 30
              successThreshold: 1
              failureThreshold: 3
              timeoutSeconds: 5
            env:
            - name: K8S_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: CILIUM_K8S_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            lifecycle:
              preStop:
                exec:
                  command:
                  - /cni-uninstall.sh
            resources:
              limits:
                memory: 500Mi
              requests:
                cpu: 100m
                memory: 128Mi
            securityContext:
              seLinuxOptions:
                level: s0
                type: spc_t
              capabilities:
                add:
                - CHOWN
                - KILL
                - NET_ADMIN
                - NET_RAW
                - IPC_LOCK
                - SYS_MODULE
                - SYS_ADMIN
                - SYS_RESOURCE
                - DAC_OVERRIDE
                - FOWNER
                - SETGID
                - SETUID
                drop:
                - ALL
            terminationMessagePolicy: FallbackToLogsOnError
            volumeMounts:
            - name: bpf-maps
              mountPath: /sys/fs/bpf
              mountPropagation: Bidirectional
            - name: cilium-run
              mountPath: /var/run/cilium
            - name: cni-path
              mountPath: /host/opt/cni/bin
            - name: etc-cni-netd
              mountPath: /host/etc/cni/net.d
            - name: clustermesh-secrets
              mountPath: /var/lib/cilium/clustermesh
              readOnly: true
            - name: cilium-config-path
              mountPath: /tmp/cilium/config-map
              readOnly: true
            - name: lib-modules
              mountPath: /lib/modules
              readOnly: true
            - name: xtables-lock
              mountPath: /run/xtables.lock
            - name: hubble-tls
              mountPath: /var/lib/cilium/tls/hubble
              readOnly: true
          hostNetwork: true
          initContainers:
          - name: mount-cgroup
            image: quay.io/cilium/cilium:v1.16.1
            imagePullPolicy: IfNotPresent
            env:
            - name: CGROUP_ROOT
              value: /run/cilium/cgroupv2
            command:
            - sh
            - -ec
            - |
              cp /usr/bin/cilium-mount /hostbin/cilium-mount;
              nsenter --cgroup=/hostproc/1/ns/cgroup --mount=/hostproc/1/ns/mnt "${BIN_PATH}/cilium-mount" $CGROUP_ROOT;
              rm /hostbin/cilium-mount
            volumeMounts:
            - name: hostproc
              mountPath: /hostproc
            - name: cgroup
              mountPath: /run/cilium/cgroupv2
              mountPropagation: Bidirectional
            - name: cilium-bin-dir
              mountPath: /hostbin
            securityContext:
              seLinuxOptions:
                level: s0
                type: spc_t
              capabilities:
                add:
                - SYS_ADMIN
                - SYS_CHROOT
                - SYS_PTRACE
                drop:
                - ALL
            terminationMessagePolicy: FallbackToLogsOnError
          - name: apply-sysctl-overwrites
            image: quay.io/cilium/cilium:v1.16.1
            imagePullPolicy: IfNotPresent
            env:
            - name: BIN_PATH
              value: /opt/cni/bin
            command:
            - sh
            - -ec
            - |
              cp /usr/bin/cilium-sysctlfix /hostbin/cilium-sysctlfix;
              nsenter --mount=/hostproc/1/ns/mnt "${BIN_PATH}/cilium-sysctlfix";
              rm /hostbin/cilium-sysctlfix
            volumeMounts:
            - name: hostproc
              mountPath: /hostproc
            - name: cilium-bin-dir
              mountPath: /hostbin
            securityContext:
              seLinuxOptions:
                level: s0
                type: spc_t
              capabilities:
                add:
                - SYS_ADMIN
                - SYS_CHROOT
                - SYS_PTRACE
                drop:
                - ALL
            terminationMessagePolicy: FallbackToLogsOnError
          - name: mount-bpf-fs
            image: quay.io/cilium/cilium:v1.16.1
            imagePullPolicy: IfNotPresent
            args:
            - 'mount | grep "/sys/fs/bpf type bpf" || mount -t bpf bpf /sys/fs/bpf'
            command:
            - /bin/bash
            - -c
            - --
            terminationMessagePolicy: FallbackToLogsOnError
            securityContext:
              privileged: true
            volumeMounts:
            - name: bpf-maps
              mountPath: /sys/fs/bpf
              mountPropagation: Bidirectional
          - name: clean-cilium-state
            image: quay.io/cilium/cilium:v1.16.1
            imagePullPolicy: IfNotPresent
            command:
            - /init-container.sh
            env:
            - name: CILIUM_ALL_STATE
              valueFrom:
                configMapKeyRef:
                  key: clean-cilium-state
                  name: cilium-config
                  optional: true
            - name: CILIUM_BPF_STATE
              valueFrom:
                configMapKeyRef:
                  key: clean-cilium-bpf-state
                  name: cilium-config
                  optional: true
            - name: WRITE_CNI_CONF_WHEN_READY
              valueFrom:
                configMapKeyRef:
                  key: write-cni-conf-when-ready
                  name: cilium-config
                  optional: true
            terminationMessagePolicy: FallbackToLogsOnError
            securityContext:
              seLinuxOptions:
                level: s0
                type: spc_t
              capabilities:
                add:
                - CHOWN
                - KILL
                - NET_ADMIN
                - NET_RAW
                - IPC_LOCK
                - SYS_MODULE
                - SYS_ADMIN
                - SYS_RESOURCE
                - DAC_OVERRIDE
                - FOWNER
                - SETGID
                - SETUID
                drop:
                - ALL
            volumeMounts:
            - name: bpf-maps
              mountPath: /sys/fs/bpf
            - name: cilium-cgroup
              mountPath: /run/cilium/cgroupv2
              mountPropagation: HostToContainer
            - name: cilium-run
              mountPath: /var/run/cilium
            - name: cni-path
              mountPath: /host/opt/cni/bin
            - name: etc-cni-netd
              mountPath: /host/etc/cni/net.d
            - name: cilium-config-path
              mountPath: /tmp/cilium/config-map
              readOnly: true
            resources:
              requests:
                cpu: 100m
                memory: 100Mi
          - name: install-cni-binaries
            image: quay.io/cilium/cilium:v1.16.1
            imagePullPolicy: IfNotPresent
            command:
            - /install-plugin.sh
            resources:
              requests:
                cpu: 100m
                memory: 10Mi
            securityContext:
              seLinuxOptions:
                level: s0
                type: spc_t
              capabilities:
                drop:
                - ALL
            terminationMessagePolicy: FallbackToLogsOnError
            volumeMounts:
            - name: cni-path
              mountPath: /host/opt/cni/bin
          nodeSelector:
            kubernetes.io/os: linux
          priorityClassName: system-node-critical
          serviceAccount: cilium
          serviceAccountName: cilium
          terminationGracePeriodSeconds: 1
          tolerations:
          - operator: Exists
          volumes:
          - name: cilium-run
            hostPath:
              path: /var/run/cilium
              type: DirectoryOrCreate
          - name: bpf-maps
            hostPath:
              path: /sys/fs/bpf
              type: DirectoryOrCreate
          - name: hostproc
            hostPath:
              path: /proc
              type: Directory
          - name: cilium-cgroup
            hostPath:
              path: /run/cilium/cgroupv2
              type: DirectoryOrCreate
          - name: cni-path
            hostPath:
              path: /opt/cni/bin
              type: DirectoryOrCreate
          - name: etc-cni-netd
            hostPath:
              path: /etc/cni/net.d
              type: DirectoryOrCreate
          - name: lib-modules
            hostPath:
              path: /lib/modules
          - name: xtables-lock
            hostPath:
              path: /run/xtables.lock
              type: FileOrCreate
          - name: clustermesh-secrets
            projected:
              sources:
              - secret:
                  name: cilium-clustermesh
                  optional: true
              - secret:
                  name: clustermesh-apiserver-remote-cert
                  optional: true
              defaultMode: 0400
          - name: cilium-config-path
            configMap:
              name: cilium-config
          - name: cilium-bin-dir
            hostPath:
              path: /opt/cni/bin
              type: DirectoryOrCreate
          - name: hubble-tls
            projected:
              sources:
              - secret:
                  name: hubble-server-certs
                  optional: true
              defaultMode: 0400
    ---
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: cilium-operator
      namespace: kube-system
      labels:
        io.cilium/app: operator
        name: cilium-operator
    spec:
      replicas: 2
      selector:
        matchLabels:
          io.cilium/app: operator
          name: cilium-operator
      strategy:
        rollingUpdate:
          maxSurge: 25%
          maxUnavailable: 50%
        type: RollingUpdate
      template:
        metadata:
          labels:
            io.cilium/app: operator
            name: cilium-operator
        spec:
          containers:
          - name: cilium-operator
            image: quay.io/cilium/operator-generic:v1.16.1
            imagePullPolicy: IfNotPresent
            command:
            - cilium-operator-generic
            args:
            - --config-dir=/tmp/cilium/config-map
            - --debug=$(CILIUM_DEBUG)
            env:
            - name: K8S_NODE_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
            - name: CILIUM_K8S_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: CILIUM_DEBUG
              valueFrom:
                configMapKeyRef:
                  key: debug
                  name: cilium-config
                  optional: true
            livenessProbe:
              httpGet:
                host: "127.0.0.1"
                path: /healthz
                port: 9234
                scheme: HTTP
              initialDelaySeconds: 60
              periodSeconds: 10
              timeoutSeconds: 3
            readinessProbe:
              httpGet:
                host: "127.0.0.1"
                path: /healthz
                port: 9234
                scheme: HTTP
              initialDelaySeconds: 0
              periodSeconds: 5
              timeoutSeconds: 3
              failureThreshold: 5
            volumeMounts:
            - name: cilium-config-path
              mountPath: /tmp/cilium/config-map
              readOnly: true
            terminationMessagePolicy: FallbackToLogsOnError
          hostNetwork: true
          nodeSelector:
            kubernetes.io/os: linux
          priorityClassName: system-cluster-critical
          serviceAccount: cilium-operator
          serviceAccountName: cilium-operator
          tolerations:
          - operator: Exists
          volumes:
          - name: cilium-config-path
            configMap:
              name: cilium-config
    ---
    apiVersion: v1
    kind: ConfigMap
    metadata:
      name: cilium-config
      namespace: kube-system
    data:
      identity-allocation-mode: crd
      cilium-endpoint-gc-interval: 5m0s
      nodes-gc-interval: 5m0s
      skip-cnp-status-startup-clean: "false"
      
      # Cluster name identification: this name will be displayed in Hubble
      cluster-name: default
      
      # Cluster ID: unique cluster identifier, if you intend to connect multiple clusters.
      cluster-id: "0"
      
      # Configure the encapsulation configuration for communication between nodes.
      # Possible values:
      #   - disabled
      #   - vxlan (default)
      #   - geneve
      tunnel: vxlan
      
      # Enables L7 proxy for L7 policy enforcement and visibility
      enable-l7-proxy: "true"
      
      # wait for kernel to come up and settle
      # (avoids network flakes in some environments)
      agent-not-ready-taint-key: "node.cilium.io/agent-not-ready"
      
      # Configure service load-balancing
      enable-local-redirect-policy: "false"