apiVersion: addons.cluster.x-k8s.io/v1beta1
kind: ClusterResourceSet
metadata:
  name: calico-crs
  namespace: default
spec:
  strategy: ApplyOnce
  clusterSelector:
    matchLabels:
      cni: calico
  resources:
  - name: calico-addon
    kind: ConfigMap