apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: myproxmoxcluster-workers
  namespace: default
spec:
  #clusterName: myproxmoxcluster
  replicas: 1
  selector:
    matchLabels: null
  template:
    metadata:
      labels:
        node-role.kubernetes.io/node: ""
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
          name: myproxmoxcluster-worker
      clusterName: myproxmoxcluster
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1alpha1
        kind: ProxmoxMachineTemplate
        name: myproxmoxcluster-worker
      version: v1.32.0